Update gpnf-limit-entry-min-max-from-field.php
Fixing these two issues:
1. Creation of dynamic property GP_Nested_Forms_Dynamic_Entry_Min_Max::$_args is deprecated

2. Uncaught TypeError: self.maxFieldId.replace is not a function